#!/bin/bash

source common.sh
cd $SRCDIR

for ((i=1;i<=$KSUBVER;i++)) ; do
    git checkout -fq v$KMAINVER.${i}
    echo -ne "v$KMAINVER.${i}\t"
    echo "$(git diff v$KMAINVER.$(($i-1))..v$KMAINVER.$i -- drivers | grep -A 1 -- '^--- /dev/null$' | sed -n -e 's/^+++ b\/\(.*\.[chS]\)$/\1/p' | xargs wc -l | tail -1 | awk '{print $1}')" 
done
