#!/bin/bash

source common.sh
cd $SRCDIR

# for ((i=12;i<=39;i++)) ; do
#     git log --oneline v2.6.$(($i-1))..v2.6.$i | wc -l
# done
#
# git log --oneline v2.6.39..v3.0 | wc -l
#
# for ((i=1;i<=19;i++)) ; do
#     git log --oneline v3.$(($i-1))..v3.$i | wc -l
# done
#
# git log --oneline v3.19..v4.0 | wc -l
#
# for ((i=1;i<=10;i++)) ; do
#     git log --oneline v4.$(($i-1))..v4.$i | wc -l
# done

for ((i=1;i<=$KSUBVER;i++)) ; do
    echo -e "v$KMAINVER.${i}\t $1 patches total:"
    git log --oneline --author=$1 v$KMAINVER.$(($i-1))..v$KMAINVER.$i | wc -l

    echo -e "v$KMAINVER.${i}\t $1 patches subsystem total:"
    for d in arch block crypto drivers fs init ipc kernel lib mm net security sound virt ; do
	echo -e "$d  $(git log --oneline --author=$1 v$KMAINVER.$(($i-1))..v$KMAINVER.$i ./$d | wc -l)"
	# echo -ne "$(find $d -type f -name '*.[chS]' -exec wc -l {} \; | awk 'BEGIN{sum=0}{sum+=$1}END{print sum}')\t"
    done
    echo

    echo -e "v$KMAINVER.${i}\t $1 patches drivers total:"
    for d in $(find $SRCDIR/drivers/ -maxdepth 1 -type d | sed -e '/.*drivers\/$/d' | sort) ; do
	    TMP=$(basename $d)
	    echo "$TMP  $(git log --oneline --author=$1 v$KMAINVER.$(($i-1))..v$KMAINVER.$i ./drivers/$TMP | wc -l)"
    done
done
